services:
  prod_api:
    depends_on:
      prod_db:
        condition: service_healthy
    build:
      context: .
      target: production
    container_name: PROD_NODE_CONTAINER
    command: ['node', 'dist/index.js']
    restart: unless-stopped
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env.production

  prod_db:
    image: postgres:latest
    container_name: PROD_POSTGRES_CONTAINER
    restart: unless-stopped
    environment:
      POSTGRES_USER: docker_prod_user
      POSTGRES_PASSWORD: docker_prod_password
      POSTGRES_DB: docker_prod_db
    ports:
      - '5432:5432'
    volumes:
      - prod_pgdata:/var/lib/postgresql
      # - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docker_prod_user -d docker_prod_db']
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  prod_pgdata:
