name: dev_express_psql
services:
  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      target: development
    container_name: NODE_CONTAINER
    entrypoint: ['/app/docker-entrypoint.sh']
    command: ['npm', 'run', 'dev']
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  db:
    image: postgres:latest
    container_name: POSTGRES_CONTAINER
    restart: unless-stopped # Or: always
    environment:
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: docker_password
      POSTGRES_DB: docker_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docker_user -d docker_db']
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  node_modules:
  pgdata:
