name: CI

on:
  # Only add on push if you plan on using Render to also check tests.
  # It's what Render's "After CI Checks Pass" needs.
  # push:
  #   branches: [main]

  # This runs when the PR is created, NOT when a merge is made.
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  # ⚠️ Gotcha: Make sure the branch protection rule on main now
  # uses this for required status checks: "test / reusable-test"
  test:
    uses: ./.github/workflows/reusable-test.yml
