name: Playground
## Currently, this is running everything against node-version 24, but what
## if we want to actually run all the tests against a Docker image?
## Review: Corresponds to lesson 8 in the FEM course.
## https://github.com/ALT-F4-LLC/fem-cicd-service/blob/poc/.github/workflows/deploy.yml

#! We don't want this to run on pull_request to main.
on:
  push:
    branches: [development]
  workflow_dispatch:

jobs:
  random-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Use Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'

      - name: Install Deps
        run: npm ci
        # This is necessary. Otherwise, you'll run into a TypeScript error during the Type Check step.
        # ❌ Cannot find module '@/generated/prisma/client' or its corresponding type declarations.
      - name: Generate Prisma Client
        run: npx prisma generate --config ./prisma.config.ts
        env:
          # Decide if your tests need a real database.
          # If any Vitest test actually needs to talk to a real database (not just have Prisma Client generated),
          # a dummy DATABASE_URL won't be enough — you'd need a Postgres service container in the workflow.
          # If your tests mock the DB layer or don't touch it, the dummy value above is sufficient.
          DATABASE_URL: postgresql://dummy_user:dummy_password@localhost:5432/dummy_db

      - name: Type Check
        run: npm run typescript

      - name: Lint
        # The current package.json `npm run lint` script will not cause the CI step to fail on warnings.
        # However, in the actual CI we want it to, so we use --max-warnings=0
        # ❌ run: npm run lint
        run: npx eslint src --max-warnings=0

  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        run: echo "${{ toJSON(github) }}"

  finished:
    needs: random-job
    runs-on: ubuntu-latest
    # if: always() Execution: Ensures the finished job executes even if random-job fails,
    # allowing you to catch errors or log notifications regardless of outcome.
    if: always()
    steps:
      - name: Generate Base Summary
        run: |
          echo "## 🚀 CI Pipeline Results" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered By:** \`${{ github.actor }}\` on \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - name: Log Success
        if: needs.random-job.result == 'success'
        run: |
          echo "### Status: ✅ All checks passed successfully!" >> $GITHUB_STEP_SUMMARY

      - name: Log Failure & Exit
        if: needs.random-job.result != 'success'
        run: |
          echo "### Status: ❌ Type check or Lint checks failed." >> $GITHUB_STEP_SUMMARY
          exit 1
